# Generated by Django 3.1.2 on 2020-10-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timebank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='credits',
        ),
    ]
