# Generated by Django 3.1.2 on 2020-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebank', '0002_auto_20201003_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='cname',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
