# Generated by Django 3.1.2 on 2020-10-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebank', '0004_auto_20201003_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
    ]
